### ISSUE TITLE
Add Game Music/Atmosphospheric Sound.

### ISSUE THREAD

**Issue by sarcoma** [sarcoma/Drone-Squadron-JS-V3ish#2]
It'd be great to add some retro backing sound to the game. I'd prefer original works, if you have something that think would be suitable, it'd be great to hear it.

**Comment by sarcoma** [comment]
@edikxl That'd be great thanks so much, let me know if you have any questions at all.

**Comment by edikxl** [comment]
@sarcoma I have written my code, but, as I understand, I should build your game. I can pull sources and you will build after or if it's uncomfortable for you I can build and then pull. I guess my code works, but there can be stupid mistakes. So, what should I do?

**Comment by edikxl** [comment]
Night isn't the best time to wait answer, so i'm installing npm/webpack.

**Comment by sarcoma** [comment]
If you submit a PR I'll pull it down and see where you at. I'm not sure the best way otherwise, I'm not entirely sure I follow what you're saying.

Have you run `npm install` or `yarn install` or something. After that check in the package.json there are a couple of scripts that can be run to build it. `npm run watch` or `npm run build` will do the trick.

**Comment by sarcoma** [comment]
Yeah sure sound good.

If you have npm installed, you should just have to run `npm install` then `npm run watch`. It should sort itself out, see how you get on. Let me know if anything goes wrong and I'll see what I can do to guide you through it.

I'll be clocking off now though, but I can get back to you in the morning.

**Comment by edikxl** [comment]
I have built, and my script is in bundle.js So, I need only debug my code a bit. Thank you for your help.
